.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/contribution-proposal.md
README.md
apps/website/get-started/README.md
apps/website/get-started/developing/README.md
docs/CODING_GUIDELINES.md
docs/CONTRIBUTING_DESIGN.md
docs/CONTRIBUTING_DEVELOPMENT.md
docs/CONTRIBUTING_DOCUMENTATION.md
docs/CONTRIBUTING_ISSUES.md
docs/GOVERNANCE.md
packages/angular/projects/cds-angular/package.json
packages/core/docs/angular.stories.mdx
packages/core/docs/angularjs.stories.mdx
packages/core/docs/development/demo-applications.stories.mdx
packages/core/docs/development/getting-started.stories.mdx
packages/core/docs/development/unit-testing.stories.mdx
packages/core/docs/preact.stories.mdx
packages/core/docs/react.stories.mdx
packages/core/docs/vue.stories.mdx
packages/core/docs/welcome.stories.ts
packages/core/npm.json
packages/core/src/styles/themes/clr-theme.stories.mdx
packages/eslint-plugin-clarity-adoption/package.json
packages/react/package.json
packages/schematics/package.json

Signed-off-by: Cory Rylan <splintercode.cb@gmail.com>
Updating urls for new repos. Forgot to do this on my fork so will delete topic branch once merged on beta and main.

chore: update repo urls

---

.github/workflows/build.yml

Fixes repo name check to enable build ci to run on new repo

chore: github build action (main)

---

.github/workflows/build.yml

Fixes repo name check to enable build ci to run on new repo

chore: github build action (beta)

---

packages/core/src/icon/index.ts

Signed-off-by: Scott Mathis <smathis@vmware.com>
Digital signature icon and iconname weren't being exported from `@cds/icon`
Issue Number: #17 
Now they are!

fix(core:icon): export digital signature icon

---

projects/core/custom-elements.json
projects/core/src/internal-components/overlay/overlay.element.spec.ts
projects/core/src/internal-components/overlay/overlay.element.ts
projects/core/src/internal/positioning/utils.spec.ts
projects/core/src/modal/modal.stories.ts

A prior fix for animations broke native behavior for the hidden attribute.
- This sets hidden to default to false to preserve the native `hidden` attribute behavior. When the `hidden` attribute exists on the host element it is true and if its removed then it is false.
- Also fixes a script path causing the CI to fail on a non-existing directory

fix: hidden attr

---

projects/core/custom-elements.json
projects/core/src/icon/index.ts

Fixes #40
Launchpad icon isn't exported with other icons
Issue Number: #40

fix(icon): export launchpad icon

---

.github/workflows/build.yml
.github/workflows/demo.yml
projects/core/src/alert/alert-group.element.scss
projects/core/src/alert/alert-group.element.spec.ts
projects/core/src/alert/alert-group.element.ts
projects/core/src/alert/alert-group.stories.ts
projects/core/src/alert/alert.element.scss
projects/core/src/alert/alert.element.ts
projects/core/src/alert/banner-alerts.stories.mdx
projects/core/src/pagination/pagination.element.scss
projects/core/src/pagination/pagination.element.spec.ts
projects/core/src/pagination/pagination.element.ts

- adds missing storybook demo for pagination alerts
- clean/refactor CSS related to alert pagination

chore: alert pager demo

---

.github/workflows/build.yml
.github/workflows/demo.yml

Fix publish/demo path for CI PR task

chore: fix ci demo path

---

projects/core/src/styles/shim.clr-ui.scss

Addresses #71
Issue Number: #71
Updates shim colors to more closely match core

fix(shim): update shim colors for components that exist in core

---

projects/core/.storybook/manager-head.html

Fix analytics reporting for core storybook

chore: send analytics pageviews for storybook

---

projects/react/package.json

chore(react): upgrade jest version

---

.github/workflows/pr-build.yml
.github/workflows/pr-preview.yml
.github/workflows/release-preview.yml
.github/workflows/release.yml

CI related changes
- The deployment steps and artifacts are named "demo".
- The artifact is downloaded from the most recent successful PR Build workflow run.
- The deployment steps and artifacts are named "storybook".
- The artifact is downloaded from the specific PR Build workflow run that triggered the deployment workflow.
No

chore: various fixes for deployment workflows

---

projects/adoption/package.lib.json
projects/angular/projects/cds-angular/package.json
projects/core/package.lib.json
projects/react/package.lib.json

Other: Package manifest update
npmjs.org links to https://clarity.design.
npmjs.org will link to https://core.clarity.design after this is released.

feat: update homepage in package manifests

---

projects/core/src/tag/tag.element.scss
projects/core/src/tag/tag.stories.ts

fix(tag): remove hover bg color change when disabled (backport)

---

projects/core/src/alert/alert.element.scss
projects/core/src/alert/alert.element.spec.ts

- flexbox has some quirks with overflow
- setting min-width: 0 prevents the content from overflowing
fixes #137

fix(alert): prevent content from overflowing alert (backport)

---

projects/core/src/file/file.stories.mdx

This was brought up on slack and I explained a workaround, but figured I should document it

chore: update cds-file docs for react usage

---

projects/react/App.tsx
projects/react/index.html

This was all one big component before and it was annoying to navigate

chore: split react demo into components

---

projects/core/custom-elements.json
projects/core/src/navigation/navigation.element.spec.ts
projects/core/src/navigation/navigation.element.ts

fix(navigation): sync state with newly added nav items (backport)

---

projects/core/src/textarea/textarea.element.scss

fix(textarea): update disabled text color (backport)

---

projects/core/src/forms/control-inline/control-inline.element.ts

closes #198
Bugfix
Checkbox/radio elements are not focused on click of the checkbox/radio. 
Issue Number: #198
Checkbox/radio elements are focused on click of the checkbox/radio. 
No.

fix(forms): focus checkbox/radio elements on click

---

projects/core/rollup.utils.js

- [ x] Bugfix
- [ x] Build related changes
The exports field in the published package.json incorrectly mapped the root index file with the key "./", which is invalid. 
Correctly maps the root index file for ".", which is valid. 
- [x ] No

fix(package): correctly publish root file export

---

projects/core/src/icon/icon.stories.ts

To be used when adding and testing new icons.
Only all icons can be viewed in Storybook without any sorting or categorization.
"Collections" page was added, where icons are organized by collection.

chore: add collections page to storybook icons

---

projects/core/package.json

This fixes a mistake I made in 7793a2697a76fe2d9bece7626ce4cae4b0256fcf.
closes #231

fix: revert `@types/ramda` update to resolve `ts-toolbelt` issues

---

projects/core/.storybook/manager-head.html

Update Storybook analytics to use GA4 and gtag.

chore(analytics): update storybook to use ga4

---

README.md

Updates the readme to match the library name rather than the system.

chore: add title to the readme

---

projects/core/src/styles/tokens/tokens.stories.ts

Before | After
--- | ---
- I brought this up on our internal Slack: https://cloudhealth.slack.com/archives/C0JF8D2LB/p1688161816165889
- I also had the following questions on that thread (I'll update this PR description if I get an answer there, to hopefully help others):
- Is it actually expected that the default and selected variants have the same color? Same question about hover vs. active
- What does active vs. selected mean? I understand all other states (default, hover, disabled, focused), and I understand there is a need for a state when an item is “on”, but when that’s the case I’m not sure to understand which one to choose between `active` vs. `selected`, could you advise?

chore: use valid design tokens for selected color of horizontal nav and tab stories

---

projects/core/build/tokens.ts

- [] Feature
Reverts the change to the `--cds-alias-object-interaction-color` token. This token previously existed as color construction 700 and was recently updated to color construction 500.
This PR reverts the change to the color and restores its previous value (color construction 700).

fix(color): revert object-interaction-color change

---

projects/core/build/tokens.ts
projects/core/sandbox/index.html
projects/core/src/checkbox/checkbox.stories.ts
projects/core/src/grid/docs/kitchen-sink.story.ts
projects/core/src/index.performance.ts
projects/core/src/radio/radio.stories.ts
projects/core/src/selection-panels/checkbox/checkbox-panel.stories.ts
projects/core/src/selection-panels/radio/radio-panel.stories.ts
projects/core/src/styles/typography/_typography.scss
projects/core/src/styles/typography/typography.stories.ts
projects/core/src/tree-view/tree.stories.ts

Adds headline typography style that is the same as the heading style. Adds a note to remove heading in v7.

feat(typography): add headline, deprecate heading

---

projects/core/src/file/file.stories.mdx

After #230 , these docs are no longer relevant

chore(file): remove react doc warning that is no longer relevant

---

projects/core/build/tokens.ts

Moves new color aliases from `object-` to `object-interaction-`

fix(tokens): update location of new interaction colors

---

projects/core/build/tokens.ts
projects/core/src/index.performance.ts

Issue Number: CDE-1111
Adds a new blue-75 token, remaps a disabled and active token per the spec.

feat(tokens): add new blue-75 token, update aliases per spec

---

projects/core/build/tokens.ts

- Body typography token line height is equal to 19.99 px.
- Body typography token letter spacing is equal to -0.2 px.
- Title typography token line height is equal to 28 px.
- Title typography token letter spacing is equal to -0.199992 px.
- Subsection typography token line height is equal to 20 px.
- Message typography token line height is equal to 20 px.
- Body typography token line height is equal to 20 px.
- Body typography token letter spacing is equal to -0.1 px.
- Title typography token line height is equal to 32 px.
- Title typography token letter spacing is equal to -0.2 px.
- Subsection typography token line height is equal to 24 px.
- Message typography …

fix(typography): body, title, subsection and message tokens

---

projects/core/src/input/input.element.scss

There is no focus indicator inside  input groups when navigation through button actions.
Issue Number: CDE-1551
Visible focus indicator.

fix(button-action): show keyboard focus indicator

---

package.json

chore(deps): update netlify-cli

---

.github/workflows/pr-preview.yml
.github/workflows/release-preview.yml
.github/workflows/release.yml

Netlify deploy fails after introducing new `netlify-cli` version here #291

chore: correct netlify deploy

---

projects/core/build/tokens.ts
projects/core/src/index.performance.ts
projects/core/src/styles/theme.dark.scss

Issue Number: CDE-2038, CDE-1923
Updates values of interactions tokens to meet requirements and add two new tokens for selected hover/active state.

feat(tokens): add/update color tokens

---

projects/core/build/tokens.ts
projects/core/src/index.performance.ts
projects/core/src/styles/theme.dark.scss

Issue Number: CDE-1513
Fixed values for core design tokens

fix: core token adjustments

---

projects/core/build/tokens.ts
projects/core/src/index.performance.ts
projects/core/src/styles/theme.dark.scss

Issue Number: [CDE-2223](https://jira.eng.vmware.com/browse/CDE-2223)

feat(vertical-nav): update design tokens for background interaction states

---

projects/core/build/tokens.ts
projects/core/src/styles/theme.dark.scss

`--cds-alias-viz-severity-warning-light` doesnt not exist.
Issue Number: CDE-2377
`--cds-alias-viz-severity-warning-light` is added for both light and dark themes.

 feat(token): add viz alias for severity warning light

---

projects/core/build/tokens.ts
projects/core/src/index.performance.ts
projects/core/src/styles/theme.dark.scss

Statis interaction `active` tokens doesnt exist.
Interaction `info-selected` token doesnt exist.
Issue Number: CDE-2473, CDE-2475
Status interaction `click` tokens are deprecated in favor of `active` with the same value.
Interaction `info-selected` token is created for dark and light themes.

fix(tokens): add interaction active and info selected tokens

---

projects/core/build/tokens.ts
projects/core/src/index.performance.ts
projects/core/src/styles/theme.dark.scss

Issue Number: [CDE-2457](https://vmw-jira.broadcom.net/browse/CDE-2457)

feat: add free space color tokens for charts

---

projects/core/build/tokens.ts
projects/core/src/index.performance.ts
projects/core/src/styles/theme.dark.scss

feat(viz-tokens): add new aliases
