vmware-clarity/core

packages/core/src/dropdown/dropdown.stories.ts
packages/core/src/grid/docs/row-action.story.ts
packages/core/src/internal-components/overlay/overlay.element.spec.ts
packages/core/src/internal-components/overlay/overlay.element.ts
packages/core/src/internal/positioning/utils.spec.ts
packages/core/src/internal/utils/dom.spec.ts
packages/core/src/internal/utils/dom.ts
packages/core/src/modal/modal.element.spec.ts
packages/core/src/modal/modal.element.ts
packages/core/src/modal/modal.stories.ts

Signed-off-by: Scott Mathis <smathis@vmware.com>
There was a regression in `6.0.0-next.4` that broke the animations for the dropdowns and modals (all overlays).
The animations for those components rely on the `hidden` property. But we had introduced an eslint to block certain keywords from being used as properties. This was to prevent Safari from breaking on the AOM when working with properties that mapped to aria attrs.
`hidden` is not an aria attr. So it doesn't seem to mess up the AOM (Accessibility Object Model - the DOM but for accessibility!).
I also addressed a few padding issues I saw in the demos for signposts, dropdowns and grid row actions.

fix(core:modal): fix modal and popup animations

---

projects/core/src/radio/radio-group.element.spec.ts
projects/core/src/radio/radio-group.element.ts

Closes #21
The cds-radio-group will automatically set a name on all radio inputs inside of it, overwriting the name attribute
Issue Number: #21 
An autogenerated name will only be set if a name doesn't already exist

fix(radio-group): allow custom input name

---

projects/core/src/radio/radio-group.element.spec.ts
projects/core/src/radio/radio-group.element.ts

Closes #21
The cds-radio-group will automatically set a name on all radio inputs inside of it, overwriting the name attribute
Issue Number: #21 
An autogenerated name will only be set if a name doesn't already exist

fix(radio-group): allow custom input name (beta)

---

projects/react/src/selection-panels/radio/__snapshots__/index.test.tsx.snap
projects/react/src/selection-panels/radio/index.test.tsx
projects/react/src/selection-panels/radio/index.tsx

CdsRadioPanel previously wrapped cds-radio, not cds-radio-panel
Fixes #24
CdsRadioPanel should export cds-radio-panel, not cds-radio
Issue Number: #24

fix(react:selection-panel): wrap cds-radio-panel instead of cds-radio (beta)

---

projects/react/src/selection-panels/radio/__snapshots__/index.test.tsx.snap
projects/react/src/selection-panels/radio/index.tsx

CdsRadioPanel previously wrapped cds-radio, not cds-radio-panel
Fixes #24
CdsRadioPanel should export cds-radio-panel, not cds-radio
Issue Number: #24

fix(react:selection-panel): wrap cds-radio-panel instead of cds-radio

---

projects/core/package.json

Running `npm run public-api:update` will now run the library build as part of the script so there are no prerequisites to running the script. This is the same way it works in the ng-clarity repo.

chore: run core library build as part of public-api:update script (beta)

---

projects/core/package.json

Running `npm run public-api:update` will now run the library build as part of the script so there are no prerequisites to running the script. This is the same way it works in the ng-clarity repo.

chore: run core library build as part of public-api:update script

---

projects/core/src/radio/radio-group.element.spec.ts
projects/core/src/radio/radio-group.element.ts

fixes #42
cds-radio-group behavior isn't applying to a cds-radio-panel. Other panels in the group don't get unselected with the radio is selected.
Issue #21 
cds-radio-panel behaves like a cds-radio inside of a cds-radio-group

fix(radio-group): treat cds-radio-panel like cds-radio

---

projects/core/src/input/input.element.scss

fixes #55
When support for the `size` attribute was added for cds-select, it removed styling from all inputs using the `size` attribute, which is something pagination relies on and caused a visual regression
Issue Number: #55 
Limit the css to `select` elements using the `size` attribute
After:

fix(input): keep input styling for input with size attributes

---

projects/core/src/input/input.element.scss

fixes #55
When support for the `size` attribute was added for cds-select, it removed styling from all inputs using the `size` attribute, which is something pagination relies on and caused a visual regression
Issue Number: #55 
Limit the css to `select` elements using the `size` attribute
After:

fix(input): keep input styling for input with size attributes (v5)

---

projects/core/src/icon/icon.element.spec.ts
projects/core/src/icon/icon.element.ts

ensure the component is connected before subscribing to the globalstateservice
Fixes #61
When an element is immediately removed from the DOM, `firstUpdated` can be called after `disconnectedCallback`, resulting in an event listener created that never gets removed.
https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#using_the_lifecycle_callbacks
Issue Number: #61 
Added a check that the component is connected before creating the event listener

fix(cds-icon): fix globalstateservice memory leak

---

projects/core/src/icon/icon.element.spec.ts
projects/core/src/icon/icon.element.ts

ensure the component is connected before subscribing to the globalstateservice
Fixes #61
When an element is immediately removed from the DOM, `firstUpdated` can be called after `disconnectedCallback`, resulting in an event listener created that never gets removed.
https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#using_the_lifecycle_callbacks
Issue Number: #61 
Added a check that the component is connected before creating the event listener

fix(cds-icon): fix globalstateservice memory leak (backport)

---

projects/core/src/navigation/navigation-group.element.ts
projects/core/src/navigation/navigation-item.element.ts
projects/core/src/navigation/navigation.element.ts
projects/core/src/navigation/navigation.stories.mdx

Moving it out of beta was an accident, this decision came out of discussion with Colin and the design team

fix(navigation): move navigation component back to beta

---

projects/core/src/pagination/pagination.element.scss
projects/core/src/pagination/pagination.stories.ts

closes #84 
closes #85
(#84) The disabled pagination button doesn't render as disabled
(#85) The pagination component automatically wraps
Issue Number: #84 #85
The disabled styling is fixed and the pagination component no longer takes up 100% width so can be combined with other content

fix(pagination): fix disabled css and remove full width

---

projects/core/src/button/button.element.scss

reverts part of https://github.com/vmware/clarity/pull/6747/
This brings back the white color on grey disabled buttons from v5, following a conversation on slack.
It reverts part of https://github.com/vmware/clarity/pull/6747/

fix(button): revert disabled button color to v5 behavior

---

projects/react/App.tsx
projects/react/index.html
projects/react/package.json

This doesn't run as part of CI. There was a broken import, and parcel was failing because of an old version of babel

chore: get react demo app working

---

projects/core/.storybook/preview.js
projects/core/build/build.tokens.ts
projects/core/src/index.performance.ts

use 20 instead of 16 - 20 is the default described in the docs
allow for 16 to be set using --cds-global-base, even if the global css doesn't load
fixes vmware-clarity/ng-clarity#138
in v5, the fallback used a default base size of 20 - the default rem size for Clarity Core and NG. In v6, that changed to 16, the default rem size for browsers
Issue Number: vmware-clarity/ng-clarity#138
Change the fall back to 20, and also bring back the calculation logic that will attempt to use the --cds-global-base size first, if it exists. This means that even if the app doesn't import all of the global CSS, they can still change their base rem size use `--cds-global-base`

fix(spacing): use base 20 fallback spacing logic

---

projects/core/.storybook/manager-head.html

Currently, storybook analytics doesn't specify which page is hit because storybook uses a query string to specify the page. This PR uses the virtual page feature of analytics and URLSearchParams to record accurate page views.

chore: record virtual page data for storybook analytics

---

projects/core/custom-elements.json
projects/core/src/modal/modal-header-actions.element.ts
projects/core/src/modal/modal.stories.mdx
projects/core/src/modal/modal.stories.ts
projects/react/src/modal/index.tsx

add header action story
closes  #107
The react wrapper used an incorrect element name, so the react component didn't get rendered in the correct slot
Issue Number: #107 
Fixes the typo, adds stories since the feature wasn't documented before

fix(modal): fix react modal-header-actions export

---

projects/core/custom-elements.json
projects/core/src/alert/alert-group.stories.ts
projects/core/src/alert/alert.element.scss
projects/core/src/alert/alert.element.ts
projects/core/src/button-action/button-action.element.spec.ts
projects/core/src/button-action/button-action.element.ts

Closes #92
The icon positioning of the close button is slightly off.
Issue Number: #92 
The close button now has the same padding on the top that the left icon and text does to they're all lined up. It  sets the padding on the bottom of the icon to 0, so as to not increase the height of the component.
There was also an icon-size attribute being set on the `cds-internal-close-button` component that wasn't being used, so I piped that through to the `cds-icon` underneath to fix the size of the icon

fix(alert): fix alert close button positioning

---

projects/adoption/package.lib.json
projects/angular/projects/cds-angular/package.json
projects/core/package.lib.json
projects/react/package.lib.json

This is backport of #119.
Other: Package manifest update
npmjs.org links to https://clarity.design.
npmjs.org will link to https://core.clarity.design after this is released.

feat: update homepage in package manifests (backport)

---

.gitignore
projects/core/src/internal-components/overlay/overlay.element.scss
projects/core/src/internal/base/base.element.scss

fixes #122
`hidden={false}` on CdsModal renders as `hidden="false"`, which isn't really valid html, but it's an issue with react. The modal then doesn't render, because of css selectors for `[hidden]`
We had CSS to handle this case in v5, but some of the overlay/popover work in v6 overwrote the CSS
Issue Number: #122 
Increase CSS specificity of the visible styling for hidden="false"
This could have been fixed alternatively with a React HOC that converts the hidden boolean value of false to undefined, which prevents the hidden attribute from being applied as expected. But in the interest of keeping the React code base as thin as possible, I put the fix into CSS that already existed for …

fix(modal): react - fix modal visibility when hidden="false"

---

projects/react/src/modal/index.test.tsx
projects/react/src/modal/index.tsx

fixes #122
This was partially resolved, but the backdrop was failing to render, and clicking on the backdrop wasn't closing the modal
Issue Number: #122 
Now a value of false is converted to undefined so the attribute isn't rendered in the DOM, which semantically is the same as a true value

fix(modal): react - convert hidden false values to undefined

---

projects/core/src/tag/tag.element.scss
projects/core/src/tag/tag.stories.ts

fixes #134
When hovering over a disabled clickable tag, the background color still changes
Issue Number: #134 
The background color no longer changes on hover, when disabled

fix(tag): remove hover bg color change when disabled

---

projects/core/src/alert/alert.element.scss
projects/core/src/alert/alert.element.spec.ts

- flexbox has some quirks with overflow
- setting min-width: 0 prevents the content from overflowing
fixes #137
Content with overflow-x: auto that would otherwise render a scrollbar in a small container are instead overflowing the alert
Issue Number: #137 
add min-width: 0 to allow content to be smaller than the implied width: https://css-tricks.com/flexbox-truncated-text/

fix(alert): prevent content from overflowing alert

---

projects/core/src/styles/typography/_typography.scss

Issue Number: #143 
The line height eraser is removed on the body tag

fix: remove margin when cds-text=body is applied to body tag

---

projects/react/package.json
projects/react/src/button/__snapshots__/index.test.tsx.snap
projects/react/src/button/index.test.tsx
projects/react/src/date/__snapshots__/index.test.tsx.snap
projects/react/src/file/__snapshots__/index.test.tsx.snap
projects/react/src/forms/__snapshots__/index.test.tsx.snap
projects/react/src/icon/__snapshots__/index.test.tsx.snap
projects/react/src/input/__snapshots__/index.test.tsx.snap
projects/react/src/pagination/__snapshots__/index.test.tsx.snap
projects/react/src/pagination/index.test.tsx
projects/react/src/password/__snapshots__/index.test.tsx.snap
projects/react/src/range/__snapshots__/index.test.tsx.snap
projects/react/src/search/__snapshots__/index.test.tsx.snap
projects/react/src/textarea/__snapshots__/index.test.tsx.snap

- adopts the fix for boolean getters and setters from https://github.com/lit/lit/issues/2799#issuecomment-1203178300
- fixes an issue introduced in PR #130 where cds-pagination-button was getting disabled="false" rendered
Upgrades to the latest version of lit-labs/react, and includes a fix for #151 
Fixes property accessors (props with get/set) in react. Adds a unit test for the disabled="false" issue

fix: upgrade lit-labs/react version

---

projects/core/custom-elements.json
projects/core/src/range/range.element.spec.ts
projects/core/src/range/range.element.ts

fixes #157
the input event doesn't fire when the value is changed in code, so listen for the property change
When the value is changed in react (or via the `.value` property in vanilla js) the track width is not updating.
Issue Number: #157
The component listens to the property change and updates the track width, since the `input` event doesn't fire in that case.

fix(range): update track width when value is changed programmatically

---

projects/core/custom-elements.json
projects/core/src/navigation/navigation.element.spec.ts
projects/core/src/navigation/navigation.element.ts

fixes  #155 #82
- previously only nav items in the initial render were synced with the top level expanded state
- add onslotchange to check for that
- move tabindex logic to slot change handler as well
- reorder component functions to match best practices
- update unit tests to check syncing after component updates
Previously, expanded state was only shared with nav items on the initial render, or when the parent navigation component had updates. Asynchronously added nav items were treated as collapses, instead of having their parent state synced
Issue Number: #155 #82
the slotchange event was added to the slot to detect when new items are added

fix(navigation): sync state with newly added nav items

---

projects/core/custom-elements.json
projects/core/src/range/range.element.spec.ts
projects/core/src/range/range.element.ts

fixes #157
the input event doesn't fire when the value is changed in code, so listen for the property change

fix(range): update track width when value is changed programmatically (backport)

---

projects/react/package.lib.json

should have been done with #152
package/yarn locks aren't properly updating to the latest lit version without this
I updated lit-labs/react in #152, but forgot to update this file, so consumer's yarn locks and package lock files aren't updating the latest version

fix(react): update lit react version in package.lib.json

---

projects/core/src/textarea/textarea.element.scss

fixes #165
The text color in a disabled textarea didn't match the color of other disabled elements
Issue Number: #165 
The color now matches the color of other disabled inputs

fix(textarea): update disabled text color

---

projects/core/src/button/button.element.spec.ts
projects/core/src/button/button.element.ts

previous logic will restore a button to enabled when switching default -> loading/error -> default, but not if the button starts in a loadingState other than default
fixes #172
When a button goes from default/undefined loading state -> loading or error -> default, the button will go from enabled -> disabled -> enabled. However, this logic didn't work if the button *starts* in a non-default loadingState
Issue Number: #172

fix(button): buttons starting with loading-state should be come enabled after

---

projects/core/src/modal/modal.element.ts
projects/core/src/modal/modal.stories.ts

fixes #174
If you don't have a cds-modal-actions element, there is no margin at the bottom of the modal. So you need the element even if you don't have any actions, which actually provides more margin than necessary due to the `gap` CSS between elements.
Issue Number: #174 
Padding is applied to the container, so will appear regardless of the elements rendered

fix(modal): add bottom margin without cds-modal-actions

---

projects/core/src/list/list.scss

fix(list): use transparent marker for accessibility (backport)

---

projects/core/src/button/button.element.spec.ts
projects/core/src/dropdown/dropdown.stories.mdx
projects/core/src/dropdown/dropdown.stories.ts
projects/core/src/grid/detail/grid-detail.element.spec.ts
projects/core/src/grid/docs/column-filter.story.ts
projects/core/src/grid/docs/column-visibility.story.ts
projects/core/src/grid/docs/footer.story.ts
projects/core/src/grid/docs/kitchen-sink.story.ts
projects/core/src/grid/docs/row-action.story.ts
projects/core/src/grid/docs/row-detail.story.ts
projects/core/src/grid/docs/row-swappable.story.ts
projects/core/src/grid/docs/rtl.story.ts
projects/core/src/grid/grid.a11y.ts
projects/core/src/internal-components/popup/popup.stories.ts
projects/core/src/internal/controllers/aria-popup-trigger.controller.spec.ts
projects/core/src/internal/controllers/aria-popup-trigger.controller.ts
projects/core/src/internal/controllers/aria-popup.controller.spec.ts
projects/core/src/internal/controllers/aria-popup.controller.stories.mdx
projects/core/src/internal/controllers/aria-popup.controller.ts
projects/core/src/internal/controllers/controller.stories.ts
projects/core/src/signpost/signpost.stories.mdx
projects/core/src/signpost/signpost.stories.ts
projects/react/App.tsx

The popup attribute conflicts with the Popup API that chromium has started implementing and results in errors logged in the console. See development status: https://chromestatus.com/feature/5463833265045504
Issue Number: #140
This renames the attribute to aria-controls, which is semantically correct. This is a breaking change
Applications will lose aria attribute setting if they don't rename the attribute in their code. The component is a beta components so this change should be acceptable.

fix(dropdown): rename popup attribute to aria-controls

---

projects/core/custom-elements.json
projects/core/src/forms/control/control.element.ts

fixes #182
The padding is set for the control action only on the initial render, in `firstUpdated`. If the element is hidden at the time, the padding will be incorrect when the element becomes visible.  
Issue Number: #182 
There's now an intersection observer listening for visibility changes that will set the padding correctly

fix(control): apply control action padding when visibility changes

---

projects/core/custom-elements.json
projects/core/src/modal/modal.element.spec.ts
projects/core/src/modal/modal.element.ts

- the slot decorator doesnt update when the slot changes, so a slot listener must be added
- a slot lister cannot be added to a slot that doesnt exist
- instead, always render the slot, but use the hidden attribute
- the slot change event will force the component to update and get the new value of the slot property
fixes #188
When the actions are supplied asynchronously, they don't show up. 
Issue Number: #188 
The slot is rendered all the time, just with a hidden attribute. A slot listener was added to make sure the component rerenders to remove the hidden attribute

fix(modal): rerender modal when action slot is added

---

projects/core/src/styles/shim.clr-ui.scss

closes #195
Fix (sort of)
The light theme shim uses a lighter background color than ng-clarity for the vertical nav.
Issue Number: #195
The light theme shim uses exactly the same background colors as ng-clarity for the vertical nav. Other themes are unaffected.
No

fix(shim): match light ng-clarity vertical nav background colors

---

projects/core/src/styles/shim.clr-ui.scss

Bugfix
There was an extra dash in the `--clr-alert-info-close-icon-color` color variable mapping.
There is not an extra dash in the `--clr-alert-info-close-icon-color` color variable mapping.
No.

fix(shim): map info alert close icon color correctly

---

projects/core/src/styles/shim.clr-ui.scss

- I worked with Colin on this.
Bugfix
The shim doesn't map the `--clr-datagrid-loading-background` color. This causes the ng-clarity light color to "leak" when using the cds dark theme.
This shim maps the `--clr-datagrid-loading-background` to `--cds-alias-object-opacity-100` and `--cds-alias-object-opacity-300` for the light and dark theme, respectively.
No.

fix(shim): add mappings for datagrid loading background color

---

projects/core/src/icon/icon.element.scss

The current `info` status icons are colored with the `shade` variant, which gives the icon a very low contrast in dark theme.
This is particularly true for regular-sized icons (i.e. smaller than `lg`):
This change aligns the info icons more closely with, well, most everything else such as `cds-button`s which are displayed using the non-shade version, as well as non-info icons. As you can tell below, the impact on light theme is negligible, but in dark theme the contrast seems much better:
And on smaller icons:

fix(icons): use the non-shade alias color for info status icons

---

projects/core/custom-elements.json
projects/core/src/icon/icon.element.scss
projects/core/src/icon/icon.element.ts
projects/core/src/icon/icon.stories.ts

Not applicable here: this is a styling fix, badge/status features are already covered by tests
Before | After
--- | ---

fix(icon): add missing `neutral` badge and status

---

projects/core/custom-elements.json
projects/core/src/internal/decorators/animate.ts
projects/core/src/internal/utils/environment.ts
projects/core/src/internal/utils/events.ts

Replace isJestTest with more general isJsdomTest.
The code had a workaround to ensure compatibility with Jest + Jsdom. The value of `process.env.JEST_WORKER_ID` was used to determine whether the execution environment was Jest. To ensure compatibility with other test frameworks, and in particular Vitest, we use a more general test to determine whether to apply the workaround.
Fixes #260
Issue Number: #260 
No errors when running tests with non-jest testing frameworks (e.g. vitest).

fix(react): fix jsdom react testing with vitest

---

projects/core/build/tokens.ts
projects/core/src/index.performance.ts
projects/core/src/styles/theme.dark.scss

Adds new colors to the token system for container background inverse.

feat(ng): add missing object-container-background-inverse colors

---

projects/core/build/tokens.ts
projects/core/package.json
projects/core/src/index.performance.ts
projects/core/src/styles/theme.dark.scss
projects/core/src/styles/theme.high-contrast.scss

The token build process depends on the Token instance to generate the tokens correctly, and deepClone does not copy symbols, so the output was incorrect (aliases were being mapped to `var(--cds-);`). 
This also adds the missing typography color changes to the themes. 
Removes lodash deepClone.

fix(tokens): fix generating typography aliases

---

projects/core/custom-elements.json
projects/core/src/accordion/accordion-header.element.scss
projects/core/src/accordion/accordion-header.element.ts

Issue Number: https://github.com/vmware-clarity/core/issues/278
`--box-shadow`, `--icon-visibility`, and `--icon-margin` CSS custom properties added to cds-accordion-header.

feat(accordion): add css custom properties

---

projects/core/src/accordion/accordion-header.element.scss

Issue Number: CDE-1557
This PR is fixing the following error that occurs on `npm start`:
A more optimal solution would be to check the osso library and our rollup.utils.js file and fix the comment issue fully

chore(ci): get rid of backticks causing npm start error

---

projects/core/custom-elements.json
projects/core/src/file/file.element.spec.ts
projects/core/src/file/file.element.ts

Feature
The `buttonLabel` property on `cds-file` can be set even though it is private. When the file selection is cleared, the button label is reset to "Browse" instead of the previous `buttonLabel` value.
Issue Number: CDE-1055
A custom button label is fully supported.
No.
- The `buttonLabel` property is now `public`.
- The is a new property named `buttonLabelForSelection`. This property is `private` and should not be set externally.

feat(file): allow custom button label

---

projects/core/src/button-action/button-action.element.scss

Issue Number: [CDE-1604](https://jira.eng.vmware.com/browse/CDE-1604)
The focus outline colour defaults to the `webkit-focus-ring-color` in dark theme on windows chrome.

fix(a11y): icon button-black focus outline does not meet 3:1 contrast minimum in dark theme

---

projects/core/src/styles/theme.dark.scss

Edit the values of the new tokens to use `construction` instead of `blue` #310

fix: use construction value for new selected tokens

---

projects/core/src/styles/typography/_typography.scss

`cds-text~='code'` have larger than surrounding font size text.
Issue Number: CDE-1660
`cds-text~='code'` have same as the than surrounding font size text.

fix(typography): use surrounding font size for inline code

---

projects/core/src/styles/theme.dark.scss

Dark Theme:
- Token `--cds-alias-status-alt` have `--cds-global-color-violet-700` value.
- Token `--cds-alias-status-alt-tint` have `--cds-global-color-violet-600` value.
- Token `--cds-alias-status-alt-shade` have `--cds-global-color-violet-900` value.
Issue Number: CDE-2297
Alt status tokens have use the light theme colors.

fix(tokens): remove alt status from dark theme

---

projects/core/src/styles/theme.dark.scss

Dark theme: 
`--cds-alias-status-warning-tint` point to `--cds-global-color-ochre-600`
`--cds-alias-status-danger-tint` point to `--cds-global-color-red-800`
Issue Number: CDE-2339
`--cds-alias-status-warning-tint` point to `--cds-global-color-ochre-900`
`--cds-alias-status-danger-tint` point to `--cds-global-color-red-900`

fix(tokens): update dark theme warning and danger tint aliases

---

projects/core/build/tokens.ts
projects/core/src/index.performance.ts
projects/core/src/styles/theme.dark.scss

Light and dark themes are using the same color `--cds-global-color-cool-gray-50` for `--cds-alias-viz-border`.
Light theme have `--cds-global-color-tangerine-700` for `--cds-alias-viz-immediate`.
Light theme have `--cds-global-color-construction-200` for `--cds-alias-object-container-background-dark`.
Dark theme have `--cds-global-color-construction-700` for `--cds-alias-object-container-background-dark`.
Issue Number: CDE-2387
Light theme have `--cds-global-color-construction-1100` for `--cds-alias-viz-border`.
Light theme have `--cds-global-color-tangerine-400` for `--cds-alias-viz-immediate`.
Light theme have `--cds-global-color-cool-gray-50` for …

fix(token): update color alias tokens 

---

projects/core/src/styles/theme.dark.scss

`--cds-alias-status-warning-dark` have `--cds-global-color-ochre-700` for dark theme.
Issue Number: CDE-2402
`--cds-alias-status-warning-dark` have `--cds-global-color-ochre-600` for dark theme.

fix(tokens): warning status dark color for dark theme
